### ISSUE TITLE
Can't find latest x64 update if a newer x86 update exists but not x64 version

### ISSUE THREAD

**Issue by zigford** [aaronparker/MDT#2]
Seems like MS have released a new CU for x86 builds of 14393 but not a x64 version.
Right now, running Get-LatestUpdates -Build 14393 returns no results because an x64 equivalent of the latest update doesn't exist.

No easy way around this, but to allow finding updates which are not the latest to be found, but that kind of goes against the simplicity of 'Get Latest Updates'

**Comment by aaronparker** [comment]
What happens if you run:
`Get-LatestUpdates -Build 14393 -SearchString '*x86'

**Comment by zigford** [comment]
Yes, that or just 'Cumulative' finds a result, but only an x86, because that is the only latest update available

**Comment by aaronparker** [comment]
Running 
`.\Get-LatestUpdate.ps1 -Build 14393 | fl`

Gives me two updates right now:

`KB   : KB4025334
Note : 2017-07 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4025334)
URL  : http://download.windowsupdate.com/c/msdownload/update/software/updt/2017/07/windows10.0-kb4025334-x64_92232fdb18a81d8c6d6c413188df2fd094a0eb29.msu

KB   : KB4025334
Note : 2017-07 Cumulative Update for Windows 10 Version 1607 for x64-based Systems (KB4025334)
URL  : http://download.windowsupdate.com/c/msdownload/update/software/updt/2017/07/windows10.0-kb4025334-x64_92232fdb18a81d8c6d6c413188df2fd094a0eb29.msu`

**Comment by zigford** [comment]
Yes, I'm getting the same results now. Looking on the catalog it appears MS have bumped updates and the x86 and x64 versions have a date modified of today.

**Comment by aaronparker** [comment]
Fixed as temporary issue with update source page.
