### ISSUE TITLE
API Not Found

### ISSUE THREAD

**Issue by Geogboe** [aaronparker/MDT#3]
Great work on this script! I'm getting:

`Invoke-WebRequest : "API not found"`

Looks like the API url has changed. This one worked for me: 

> https://support.microsoft.com/app/content/api/content/asset/en-us/4000816

**Comment by aaronparker** [comment]
Thanks, I'll check it out and update ASAP.

**Comment by aaronparker** [comment]
Updated the StartKB default value, so this should now be fixed.
