### ISSUE TITLE
compability with WMF < 5.0

### ISSUE THREAD

**Issue by mawolfram** [aaronparker/MDT#4]
https://github.com/aaronparker/MDT/blob/d4f8eae5add7c42d83462b1b5001a1277a5e7069/Updates/Get-LatestUpdate.ps1#L85

`[version]::new("0.0")` just works when you have WMF 5.0 or higher installed.
On older Versions (I've tested WMF 3 and WMF 4) you must use `New-Object System.Version("0.0")`
instead.

**Comment by aaronparker** [comment]
Thanks @mawolfram, can I assume then that you're running the script on an OS version less than Windows 10?

**Comment by mawolfram** [comment]
Yes, I run it directly on my Server 2012 R2 MDT-Server

**Comment by aaronparker** [comment]
Fixed
